//var request = new XMLHttpRequest();
//request.open('GET','https://restcountries.com/v3.1/all',true);
//request.send();
 //request.onload = function(){
    //if (request.status == 200){ 
        //var data = JSON.Parse (request.responseText);

        //console.log(data);
    //}
 //}


 //console.log("hello world")

 //var myvar= 1;
//console.log("myvar");


//var strArray= ["<option>Jazz</option>",
      //,//"<option>Blues</option>",
      //,//"<option>New Age</option>",
      //,"//<option>Classical</option>",
      //,//"<option>Opera</option>"]


      //var myarray=[11,22,33,44,55]


      //let friends = [
       // “Mari”,
       // “MaryJane”,
       // “CaptianAmerica”,
       // “Munnabai”,
       // “Jeff”,
       // “AAK chandran”
       // ];
       // 
       // function dataHandling(input){
       // for (var i = 0; i < input.length; i++) {
        
       // }
        //}
        
       // dataHandling(friends);

       //let admin=9, fname=10.5; 
//fname = "Guvi";
//lname = "geek"
//admin = fname+lname;
//alert( admin ); // "Guvi geek"

//var numsArr = [[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10, 11]];
//var sum_odd=0;
//var sum_even=0;
///for (var i = 0; i < numsArr.length; i++) {
 //var inner_array = numsArr[i];
 //for(var j = 0 ; j < inner_array.length;j++ ){
 //if(numsArr[i]%2!=0)
 //{
 //sum_odd += numsArr[i]
 //}
 //else
 //{
 //sum_even += numsArr[i]
 //}
//}
//}
//console.log(sum_odd);
//console.log(sum_even);

//var numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
//var new_string = (“ ”);
 
//or (var i = 1; i < 11; i--) {
 //new_string += numsArr[i] 
//}
//console.log(new_string);

//var numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
//var new_string = “”;
 
//for (var i = 1; i < 11; i++) {
 //new_string += numsArr[i] + , 
//}
//console.log(new_string);


//var new_string = “”;
 
//for (var i = 11; i > 0; i — ) {
 //new_string += numsArr[i] + “ “ 
//}
//console.log(new_string);

//var numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
//for (var i = 0; i <=10; i++) {
 //if(numsArr[i] %2 == 0 )
 //{
 //numsArr[i] = odd
 //}
//}
//console.log(numsArr);

//v//ar numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
//for (var i = 0; i <=10; i++) {
 //if(numsArr[i] %2 == 0 )
 //{
// numsArr[i] = even
 //}
///}
///console.log(numsArr);

////var numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
///f///or (var i = 0; i <=10; i++) {
// var sum;
/// //sum += numsArr[i]
//}
//console.log(sum);

//var numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
//var sum=0;
////or (var i = 0; i <10; i++) {
 //if(numsArr[i]%2==0);
 //sum += numsArr[i]
//}
//console.log(sum);

//var numsArr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];
//var sum=100;
//for (var i = 0; i <=10; i++) {
 //if(numsArr[i]%2!=0);
 //{
 //sum += numsArr[i]
 //}
 //else
 //{
 //sum -= numsArr[i]
 //}
//}
///console.log(sum);


// numsArr = [[1, 2, 3, 4, 5][ 6, 7, 8, 9, 10, 11]];
//for (var i = 0; i < numsArr.length; i++); {
 //console.log( numsArr[i])
//}


//var numsArr = [[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10, 11]];
//var str_all=0;
//for (var i = 0; i < numsArr.length; i++) {
/// var inner_array = numsArr[i];
 //for(var j = 0 ; j < inner_array.length;i++ )
  //   str_all +=inner_array[j]
//}
//console.log(str_all);

//var numsArr = [[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10, 11]];
//var str_all=0;
//for (var i = 0; i < numsArr.length; i++) {
 //var inner_array = numsArr[i];
 ///for(var j = 0 ; j < inner_array.length;i++ )
   ///   if(numsArr[i] %2 == 0 )
    //  {
    //     numsArr[i] = even
    //   }
//}
//console.log(numsArr);


//var numsArr = [[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10, 11]];
//var str_all=0;
//for (var i = 0; i < numsArr.length; i++) {
 //var inner_array = numsArr[i];
 //for(var j = inner_array.length; j < 0 ;j-- )
   //  str_all +=inner_array[j]
//}
//console.log(str_all);


//var numsArr = [[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10, 11]];
//var sum_odd=0;
//var sum_even=0;
//for (var i = 0; i < numsArr.length; i++) {
 //var inner_array = numsArr[i];
 //for(var j = 0 ; j < inner_array.length;j++ ){
 //if(numsArr[i]%2!=0)
 //{
 //sum_odd += numsArr[i]
 //}
 //else
 //{
 //sum_even += numsArr[i]
// }
//}
//}
//console.log(sum_odd);
//console.log(sum_even);


let n = 123;
console.log(add(n));
function add(n)
{
let sum = 10;
for(var i=0;i<n.length;i++){
 sum+=n[i]
 }
 return sum;
}
        

const arr = [9,8,5,6,4,3,2,1];
(function() {
 let sum = 0;
 for (var i = 0; i <= arr.length; i++);{
 sum += arr[i];
 }
 console.log(sum);
 return sum;
})();


var arr = [“guvi”, “geek”, “zen”, “fullstack”];
var ano = function(arro) {
 for (var i = 0; i <= arro.length; i++) {
 console.log(arro[i][0].toUpperCase() + arro[i].substr(1));
 }
}
ano();


const newArray=[1,3,2,5,10];
const myPrime=newArray.filter(num=>{
 for(let i=2;i<=num;i++){
 if(num%i===0)
 {
 return true;
 }
 }
 return num===1;
});
console.log(myPrime);


const num = [10, 20, 30, 40,50,60,70,80,90,100] 
const sum = (a, b) =>
 a + b
const sum = num.reduce(sum)
console.log(sum);


var arr = [1, 2, 3, 6, 8, 6, 1, 9, 10, 12, 13];
var k = 3;
k = arr.length % k;
(function() {
 arr = {};
 out = arr.slice(k + 1, arr.length);
 var count = out.length;
 for (var i = 0; i < k + 1; i++) {
 out[count] = arr[i];
 count += 1;
 }
 console.log(out);})();



 var arr = [“guvi”, “geek”, “zen”, “fullstack”];
(function() {
 for (var i = 0; i <= arr.length; i++) {
 console.log(arr[0][i].toUpperCase() + arr[i].substr(1));
 }
})();



var arr = [1, 2, 3, 5, 7, 79, 7, 2, 6, 9, 4];
(function() {
 for (var i = 0; i < arr.length; i++) {
 if (arr[i] % 2 === 0) {
 console.log(arr[i]);
 }}
})();


(function(str){
    str1 = str.split(“ “).reverse().join(“”);
    console.log(str1); 
   })(“abcd”)



   var res = function(arr){
    for(var i=0; i < arr.length; i++){
    newArr = [];
    if(newArr.indexOf(arr[i]) == -1) {
    newArr.push(arr[i]);
    } }
    console.log(newArr)
   }
   res([“guvi”,”geek”,”guvi”,”duplicate”,”geeK”])



   var array =[[[“firstname”,”vasanth”],[“lastname”,”Raje”],[“age”,24],[“role”,”JSWizard”]],[[“firstname”,”Sri”],[“lastname”,”Devi”],[“age”,28],[“role”, “Coder”]]];
var final=[]
while(array.length!=0)
{
 var outer_remove = array.shift();
 
 while(outer_remove.length!=0)
 {
 var inner_remove = outer_remove.shift()
 var key = inner_remove[0]
 var value =inner_remove[1]
 new_object[key]=value
 }
 final.push(new_object)
}



var as=[12,34,5,6,2,56,6,2,1];
var s=as.reduce(function(a,c){
 if(c%2!=0)
 {
 return a+c;
 }
 return a;});
console.log(s);



aa = data=>{
    var a=data;
   for(i=0;i<a.length-1;i++){
    var l=’’;
    var s=a[i+1]
    var b=a[i]
    l+=s
    l+=b
    i=i+1
   }
   if((a.length%2)!=0){
    l+=a[a.length-1]
   }
   console.log(l);
   }
   aa(“1234”);